### ISSUE TITLE
维基百科的图片打不开

### ISSUE THREAD

**Issue by BardLyf** [popcorner/cernet-ipv6-hosts#3]

**Comment by popcorner** [comment]
可以给一个示例链接么？比如具体打不开的图片的链接以及图片所在页面的链接

**Comment by BardLyf** [comment]
图片链接:https://zh.wikipedia.org/wiki/%E9%95%BF%E6%B1%9F%E6%B5%81%E5%9F%9F#/media/File:Map_of_the_Yangtze_River.gif
所在链接:https://zh.wikipedia.org/wiki/%E9%95%BF%E6%B1%9F%E6%B5%81%E5%9F%9F



------------------ 原始邮件 ------------------
发件人: "popcorner"<notifications@github.com>;
发送时间: 2019年4月12日(星期五) 晚上11:10
收件人: "popcorner/cernet-ipv6-hosts"<cernet-ipv6-hosts@noreply.github.com>;
抄送: "cn"<810089348@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [popcorner/cernet-ipv6-hosts] 维基百科的图片打不开 (#3)




可以给一个示例链接么？比如具体打不开的图片的链接以及图片所在页面的链接

**Comment by popcorner** [comment]
问题应该已经解决了，更换了可用的ip。

**Comment by BardLyf** [comment]
更新之后，维基百科打不开了。

**Comment by popcorner** [comment]
确定使用的文件是当前最新的么？我刚试了一下，wikipedia是可以正常打开的，图片也能显示

**Comment by BardLyf** [comment]
是我粘贴错文件夹了，可以显示图片了
