### ISSUE TITLE
Youtube videos still not available

### ISSUE THREAD

**Issue by PyroSoar** [popcorner/cernet-ipv6-hosts#4]
Youtube视频仍无法打开，但网页打得开
请问是否有Youtube的完整hosts记录？

**Comment by popcorner** [comment]
那就对了，这个项目不支持视频地址的，参见wiki页。
youtube视频地址数量将近十万，我们的项目总共才2000多行，以轻量化为特点，加入视频地址的代价是不能承受的。而且可能会造成潜在的性能问题。
另外根据几个月前的测试，教育网内youtube视频地址ip大多无法直连，即便加了也没有用（不过最近是否恢复暂未测试）

**Comment by PyroSoar** [comment]
好的，谢谢！
